### ISSUE TITLE
Download for v4.0.5 for 1.19-1.19.2 on Modrinth contains sources jar instead of release jar

### ISSUE THREAD

**Issue by unilock** [KrLite/Splasher#5]
I assume this was not intentional :p

<https://modrinth.com/mod/splasher/version/1.19-v4.0.5>
<img width="518" alt="image" src="https://github.com/KrLite/Splasher/assets/11802133/4495ab78-ad72-4276-b54b-0811fda83488">

(it probably goes without saying that this causes the mod to crash, with `The specified mixin 'net.krlite.splasher.mixin.MinecraftClientTrigger' was not found`)

**Comment by KrLite** [comment]
That must be my carelessness 😢 Will be fixed as soon as I'm available.

**Comment by KrLite** [comment]
Fixed.
